sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t $DOCKER_REPO .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag $DOCKER_REPO $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
    else
    docker tag $DOCKER_REPO $DOCKER_REPO:$TRAVIS_BRANCH;
    docker push $DOCKER_REPO/$TRAVIS_BRANCH:latest;
    fi
