sudo: required

language: python
python:
  - "2.7"

services:
  - docker

stages:
  - test
  - docker

jobs:
  include:
    - stage: test
      script: python setup.py test
    - stage: deploy
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        - docker build -t $DOCKER_USERNAME/cdp:latest .
        - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$DOCKER_TAG_LATEST" == 1 ]; then
          docker push $DOCKER_REPO:latest;
          else
          docker tag $DOCKER_USERNAME/cdp $DOCKER_USERNAME/cdp:$TRAVIS_BRANCH;
          docker push $DOCKER_USERNAME/cdp:$TRAVIS_BRANCH;
          fi
