sudo: required

language: python
python:
  - "2.7"

services:
  - docker

stages:
  - test
  - docker

jobs:
  include:
    - stage: test
      script: python setup.py test
    - stage: deploy
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        - export REPO=$DOCKER_USERNAME/cdp
        - docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH
        - if [ "$TRAVIS_BRANCH" == "master" || [ "$DOCKER_TAG_LATEST" == 1 ]; then
          docker tag $REPO:$TRAVIS_BRANCH $REPO:latest;
          docker tag $REPO:$TRAVIS_BRANCH $REPO:$TRAVIS_BUILD_NUMBER;
          fi
        - docker push $REPO
